#!/usr/bin/env python
import re
import urllib
import os
import sys
import readline
import shutil

DEBUG = False
INTERACTIVE = True

class FormatError (ValueError):
	pass

def metainf(path):
	from tagpy import FileRef
	return FileRef(path)

def meta_artist_and_name(path):
	meta = metainf(path)
	artist = meta.tag().artist
	name = meta.tag().title
	return (artist, name)

def set_metadata(path, artist, name, clear_comments=True):
	meta = metainf(path)
	meta.tag().artist = artist
	meta.tag().title = name
	if clear_comments:
		meta.tag().comment = ''
	meta.save()


def artist_and_name(parts):
	parts = list([p.strip() for p in parts if len(p) > 0])

	while(len(parts) > 1 and parts[0].isdigit()):
		# drop leading numeric fields
		parts.pop(0)
	
	if(len(parts) > 3):
		# if there's still more than 3 parts, drop all numeric fields
		parts = filter(lambda x: not x.isdigit(), parts)

	if len(parts) < 2:
		raise FormatError("not enough parts: %r" % (parts))
	if len(parts) == 2:
		return tuple(parts)
	else:
		return parts[0], parts[2] # assume artist - album - track

def titleize(s):
	titled = s.title()
	titled = re.subn("'[A-Z]", lambda x: x.group(0).lower(), titled)[0]
	roman_numeral = re.compile(r"\b([xiv]+)\b", re.I)
	titled = re.subn(roman_numeral, lambda x: x.group(0).upper(), titled)[0]
	return titled

def filename(args):
	joined = " - ".join(args)
	joined = joined.replace("/",'-')
	return joined

def get_meta_artist_and_name(path):
		return map(titleize, meta_artist_and_name(path))

def get_filename_artist_and_name(dirty):
	def num(char, s):
		return len(map(lambda x: x == char, s))

	def unescape_url(s):
		return urllib.unquote(s)

	def replace_if_too_many(char, replacement, s):
		num_char = num(char, s)
		num_repl = num(replacement, s)
		if num_char > num_repl:
			return s.replace(char, replacement)
		return s
	
	def replace_if_too_many_plusses(s):
		return replace_if_too_many("-", " ", s)
	
	def replace_if_too_many_dashes(s):
		return replace_if_too_many("-", " ", s)
	
	def normalize_spaces(s):
		s = s.replace("   ", " - ")
		s = re.subn(" +", " ", s)[0]
		return s

	cleaned = unescape_url(dirty)
	cleaned = cleaned.replace("_", " ")
	cleaned = replace_if_too_many_plusses(cleaned)
	cleaned = replace_if_too_many_dashes(cleaned)
	cleaned = normalize_spaces(cleaned)
	cleaned = titleize(cleaned)
	parts = cleaned.split(" - ")
	if len(parts) == 1:
		parts = cleaned.split("-")
	if DEBUG: print "Parts: %r" % (parts,)
	named_parts = artist_and_name(parts)
	return named_parts

def get_path_bits(path):
	base, file = os.path.split(path)
	name, ext = os.path.splitext(file)
	ext = ext.lower()
	return base, name, ext

def get_artist_and_name(name, path):
	try:
		artist_and_name = get_filename_artist_and_name(name)
	except FormatError, e:
		if path is None:
			return None
		print "-- warning: couldn't extract name from filename: %r" % (name,)
		artist_and_name = get_meta_artist_and_name(path)
	return artist_and_name

def rename(path, output_dir=None):
	base, name, ext = get_path_bits(path)
	if not output_dir:
		output_dir = base # whatever directory it started in
	artist_and_name = get_artist_and_name(name, path)
	return os.path.join(output_dir, "%s%s" % (filename(artist_and_name), ext)), artist_and_name


def repl(paths, output_dir=None, update_tags=True, clear_comments=False, mp3gain=False):
	global INTERACTIVE
	if not paths: paths = ["."]
	files = []
	renamed = 0
	failed = 0
	for path in paths:
		realpath = os.path.realpath(os.path.expanduser(path))
		if os.path.isfile(realpath):
			files.append(path)
		else:
			for file in os.listdir(realpath):
				_path = os.path.join(realpath, file)
				if os.path.isfile(_path):
					files.append(_path)
	print "renaming %s files..." % (len(files),)

	def confirm_artist_and_name(artist_and_name):
		global INTERACTIVE
		if INTERACTIVE:
			while True:
				response = raw_input("rename to %r ([Y]es / [n]o / [e]dit / [a]ll / [q]uit): " % (filename(artist_and_name),)).rstrip()
				if response == 'a':
					print "renaming all..."
					INTERACTIVE = False
					break
				elif response == 'n':
					print "skipping..."
					return None
				elif response == 'e':
					text = raw_input("Enter the new filename: ")
					if ' - ' in text:
						artist_and_name = map(titleize, text.split(' - ', 1))
					else:
						print "invalid name: " % (text,)
				elif response == '' or response == 'y':
					break
				elif response == 'q':
					print "quitting..."
					exit(1)
				else:
					continue
		return artist_and_name

	for file in files:
		try:
			shutil.copy(file, os.path.expanduser('~/.local/share/Trash/files'))
		except IOError:
			print "--- warning: could not make backup in trash"
			INTERACTIVE = True
		try:
			file = file.decode('utf-8')
			new_path, artist_and_name = rename(file, output_dir)
		except StandardError, err:
			print "Failed: %s - %s" % (file, err)
			failed += 1
			if DEBUG: raise
			continue
		artist_and_name = confirm_artist_and_name(artist_and_name)
		if artist_and_name is not None:
			print "--- processed: %s" % (new_path,)
			if DEBUG: continue
			treat_file(file, new_path, artist_and_name, update_tags=update_tags, clear_comments=clear_comments, mp3gain=mp3gain)
			renamed += 1
	return renamed, failed

def treat_file(file, new_path, artist_and_name, update_tags=True, clear_comments=False, mp3gain=False):
	new_path = new_path.encode('utf-8')
	shutil.move(file, new_path)
	if not update_tags: return
	try:
		set_metadata(new_path, *artist_and_name, clear_comments=clear_comments)
	except RuntimeError, e:
		print "(couldn't set metadata on song file: %s)" % (e,)
		if DEBUG: raise
	
	if mp3gain:
		apply_mp3gain(new_path)
			
def apply_mp3gain(path):
	import subprocess
	cmd = subprocess.Popen(['mp3gain', '-r', '-c', '-m', '2', '-s', 'r', path], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
	stdout, stderr = cmd.communicate()
	if cmd.returncode != 0:
		print "ERROR: mp3gain failed:\nSTDOUT: %s\n\nSTDERR: %s" % (stdout, stderr)
		if DEBUG: raise OSError("mp3gain failed!")

def notify(title, message):
	import pygtk
	import pynotify
	pynotify.init(os.path.basename(sys.argv[0]))
	pynotify.Notification(title, message).show()

def _main(argv):
	global DEBUG, INTERACTIVE
	from optparse import OptionParser
	parser = OptionParser(usage="usage: %prog [options] [input-file-or-path]")
	parser.add_option('-c','--clear-comments', dest='clear_comments', action='store_true', help='clear comments (%default)', default=False)
	parser.add_option('-o','--output', dest='output_dir', action='store', help='output directory', default=None)
	parser.add_option('-i', '--interactive', dest='interactive', action='store_true', help='interactive mode (%default)', default=True)
	parser.add_option('-q', '--quiet', dest='interactive', action='store_false', help='quiet (non-interactive) mode')
	parser.add_option('-d', '--debug', dest='debug', action='store_true', help='debug mode')
	parser.add_option('-t', '--tags', dest='update_tags', action='store_true', help='overwrite id3 tag info (%default)', default=True)
	parser.add_option('--no-tags', dest='update_tags', action='store_false')
	parser.add_option('-n', '--notify', dest='notify', action='store_true', help='notify on completion (%default)', default=True)
	parser.add_option('--no-notify', dest='notify', action='store_false', help='don\'t notify on completion')
	parser.add_option('-g', '--mp3gain', dest='mp3gain', action='store_true', help='apply mp3gain (%default)', default=False)
	parser.add_option('--test', dest='test', action='store', help='test mode (try out a string)', default=None)

	options, args = parser.parse_args(argv)
	DEBUG = options.debug
	INTERACTIVE = options.interactive
	if options.test is not None:
		print repr(options.test)
		artist_and_name = get_artist_and_name(options.test, None)
		if artist_and_name is None:
			print "ERROR: Could not parse: %s" % (options.test,)
		else:
			print filename(artist_and_name).encode('utf-8')
		return
	if options.output_dir:
		options.output_dir = options.output_dir.decode('utf-8')
	files_changed, failed = repl(args, output_dir=options.output_dir, update_tags=options.update_tags, clear_comments=options.clear_comments, mp3gain=options.mp3gain)
	if options.notify:
		message = "%s files imported" % (files_changed,)
		if failed:
			message += " - %s FAILED" % (failed,)
		notify("Music importer", message)


def main():
	import sys
	try:
		_main(sys.argv[1:])
		sys.exit(0)
	except StandardError, e:
		print "ERROR: %s" % (e,)
		raise

if __name__ == '__main__':
	main()
